paths:
  /api/product/:
    get:
      summary: Obtener a todos los productos
      tags: 
        - product
      responses:
        '200':
          description: Productos obtenidos satisfactoriamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/product'
        '500':
          description: Error interno del servidor al obtener los productos
  /api/product/{id}:
    get:
      summary: Obtener un solo producto dado su id
      tags: 
        - product
      parameters:
        - name: id
          in: path
          required: true
          schema: 
            $type: String
          description: Id del producto a buscar
      responses:
        '200':
          description: Producto obtenido satisfactoriamente
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/product'
        '500':
          description: Error interno del servidor al obtener los productos

components:
  schemas:
    product:
      type: object
      properties:
        _id: 
          type: ObjectId
          description: Id autogenerado de MongoDB
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripcion del producto
        price:
          type: Number
          description: Precio del producto
        stock:
          type: Number
          description: cantidad existente de ese producto
        category:
          type: String
          description: Categoria del producto
        status:
          type: String
          description: Disponibilidad del producto
        code:
          type: String
          description: Identificacion de ese producto 
        thumbnails:  
          type: Array
          description: Imagenes del producto
      example:
        _id: ObjectId('64f8d0d8e8649c4df8725ca4')
        title: Leche
        description: Entera
        price: 1000
        stock: 50
        category: lacteos
        status: true
        code: lac100
        thumbnails: Array vacio
        
        