paths:
  /api/product/:
    get:
      summary: Obtener todos los productos
      tags: 
        - Products
      responses:
        '200':
          description: Productos obtenidos satisfactoriamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/product'
        '500':
          description: Error interno del servidor al obtener los productos
    post:
      summary: Crear nuevo producto
      tags:
        - Products
      parameters:
          - name: Product
            in: body
            description: El producto a crear
            required: true
            schema:
                type: Object
                items:
                  $ref: '#/components/schemas/ProductToCreateOrModify'
      responses:
        '201':
          description: Producto creado satisfactoriamente
          content:
            application/json:
              schema:
                type: Object
                items:
                  $ref: '#/components/schemas/product'
        '401':
          description: Llave duplicada. El codigo del producto ya existe
        '500':
          description: Error interno del servidor al crear producto
  /api/product/{id}:
    get:
      summary: Obtener un solo producto dado su id
      tags: 
        - Products
      parameters:
          - name: id
            in: path
            description: Id del producto a buscar
            required: true
            schema: 
                type: String
      responses:
        '200':
          description: Producto obtenido satisfactoriamente
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/product'
        '500':
          description: Error interno del servidor al obtener los productos
    put:
      summary: Modificar un producto
      tags:
        - Products
      parameters:
          - name: id
            in: path
            description: Id del producto a buscar
            required: true
            schema:
                type: String
          - name: Product
            in: body
            description: El producto a modificar
            required: true
            schema:
                type: Object
                $ref: '#/components/schemas/ProductToCreateOrModify'
      responses:
        '200':
          description: Producto modificado satisfactoriamente
          content:
            application/json:
              schema:
               type: Object
               $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado
        '500':
          description: Error interno del servidor al modificar producto      
    delete:
      summary: Eliminar un producto
      tags:
        - Products
      parameters:
          - name: id
            in: path
            description: Id del producto a buscar
            required: true
            schema:
            type: String
      responses:
        '200':
          description: Producto eliminado satisfactoriamente
          content:
            application/json:
              schema:
               type: Object
               $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado
        '500':
          description: Error interno del servidor al consultar producto      
components:
  schemas:
    product:
      type: object
      properties:
        _id: 
          type: ObjectId
          description: Id autogenerado de MongoDB
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripcion del producto
        price:
          type: Number
          description: Precio del producto
        stock:
          type: Number
          description: cantidad existente de ese producto
        category:
          type: String
          description: Categoria del producto
        status:
          type: String
          description: Disponibilidad del producto
        code:
          type: String
          description: Identificacion de ese producto 
        thumbnails:  
          type: Array
          description: Imagenes del producto
      example:
        _id: ObjectId('64f8d0d8e8649c4df8725ca4')
        title: Leche
        description: Entera
        price: 1000
        stock: 50
        category: lacteos
        status: true
        code: lac100
        thumbnails: Array vacio
    productToCreateOrModify:
      type: object
      properties:
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripcion del producto
        category:
          type: String
          description: Categoria a la que pertenece el producto
        price:
          type: Number
          description: Precio del producto
        stock:
          type: Number
          description: Cantidad de productos disponibles
        code:
          type: String
          description: Codigo unico del producto
        status:
          type: Boolean
          description: Existe (true), no existe (false). -Opcional-
        thumbnail:
          type: String
          description: Imagen miniatura del producto. -Opcional-
      example:
        title: Leche
        description: semidescremada
        category: lacteos
        price: 3000
        stock: 100
        code: Lac130
        status: true
        thumbnail: Array vacio  
        